'use client';

import Head from 'next/head';
import Image from 'next/image';
import ChatPopup from '@components/ChatPopup';

export default function Home() {
  return (
    <>
      <Head>
        <title>Process Guru</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/processGuruLogo.png" />
      </Head>
      <main className="relative">
        <Image
          className="z-0 absolute"
          src="/images/intraNetBg.jpg"
          width={1366}
          height={5000}
          alt="intranet"
        />
        <ChatPopup />
      </main>
    </>
  );
}
