'use client';

import Head from 'next/head';
import Image from 'next/image';
import ChatPopup from '@components/ChatPopup';

export default function Home() {
  return (
    <>
      <Head>
        <title>Process Guru</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/processGuruLogo.png" />
      </Head>
      <main className="relative">
        {/* <div className="z-0 absolute bg-gradient-to-r from-indigo-500 from-10% via-sky-500 via-30% to-emerald-500 to-90% h-screen w-full"></div> */}
        <ChatPopup />
      </main>
    </>
  );
}
